/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Object.Player;
import System.Database;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dave van Rijn, Student 500714558, Klas IS202
 */
public class AddScores extends javax.swing.JPanel {

    private final Database db = new Database();
    private ArrayList<Player> players;
    private boolean puntenPage;
    private final DefaultTableModel model;
    private final String WEEK1 = "Week 1";
    private final String WEEK2 = "Week 2";
    private final String WEEK3 = "Week 3";
    private final String WEEK4 = "Week 4";
    private final String WEEK5 = "Week 5";
    private final String WEEK6 = "Week 6";
    private final String WEEK7 = "Week 7";
    private final String WEEK8 = "Week 8";
    private final String WEEK9 = "Week 9";
    private final String WEEK10 = "Week 10";
    private final String WEEK11 = "Week 11";
    private final String WEEK12 = "Week 12";
    private final String WEEK13 = "Week 13";
    private final String WEEK14 = "Week 14";
    private final String WEEK15 = "Week 15";
    private final String WEEK16 = "Week 16";
    private final String WEEK17 = "Week 17";
    private final String WEEK18 = "Week 18";
    private final String WEEK19 = "Week 19";
    private final String WEEK20 = "Week 20";
    private final String WEEK21 = "Week 21";
    private final String WEEK22 = "Week 22";
    private final String WEEK23 = "Week 23";
    private final String WEEK24 = "Week 24";
    private final String WEEK25 = "Week 25";
    private final String WEEK26 = "Week 26";

    /**
     * Creates new form AddScores
     */
    public AddScores(boolean puntenPage) {
        this.puntenPage = puntenPage;
        initComponents();
        model = (DefaultTableModel) tblScores.getModel();
        buildTable(WEEK1);
        setLabelText(WEEK1);
    }

    private void buildTable(String selected) {
        model.setRowCount(0);
        int weekNumber = Integer.parseInt(selected.split(" ")[1]);
        players = db.getPlayers();
        for (Player p : players) {
            Object[] data = new Object[4];
            data[0] = p.getId();
            data[1] = p.getFullname();
            int points = p.getPoints()[weekNumber - 1];
            int mars = p.getMars()[weekNumber - 1];
            if (points == 0) {
                data[2] = null;
            } else {
                data[2] = points;
            }

            if (mars == 0) {
                data[3] = null;
            } else {
                data[3] = mars;
            }
            model.addRow(data);
        }
    }

    private void setLabelText(String text) {
        lblWeek.setText(text);
        int size = (int) lblWeek.getSize().getWidth();
        int x = (int) (this.getSize().getWidth() - size) / 2;
        lblWeek.setLocation(x, (int) lblWeek.getLocation().getY());
    }

    private void opslaan() {
        for (int i = 0; i < players.size(); i++) {
            int id = (int) tblScores.getValueAt(i, 0);
            String string = (tblScores.getValueAt(i, 2) != null)?tblScores.getValueAt(i, 2).toString():null;
            int score;
            if (string != null) {
                score = Integer.parseInt(tblScores.getValueAt(i, 2).toString());
            } else {
                score = 0;
            }
            string = (tblScores.getValueAt(i, 3) != null)?tblScores.getValueAt(i, 3).toString():null;
            int mars;
            if (string != null) {
                mars = Integer.parseInt(string);
            } else {
                mars = 0;
            }
            int week = Integer.parseInt(cmbWeek.getSelectedItem().toString().split(" ")[1]);
            db.setScores(id, week, score, mars);
        }
        JOptionPane.showMessageDialog(null, "De scores zijn opgeslagen.", "Succes",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblScores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbWeek = new javax.swing.JComboBox();
        lblWeek = new javax.swing.JLabel();
        btnOpslaan = new javax.swing.JButton();
        btnAnnuleren = new javax.swing.JButton();

        tblScores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblScores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nummer", "Naam", "Punten", "Marsen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblScores.setRowHeight(30);
        tblScores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblScores);
        if (tblScores.getColumnModel().getColumnCount() > 0) {
            tblScores.getColumnModel().getColumn(0).setResizable(false);
            tblScores.getColumnModel().getColumn(1).setResizable(false);
            tblScores.getColumnModel().getColumn(2).setResizable(false);
            tblScores.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kies een week:");

        cmbWeek.setModel(new javax.swing.DefaultComboBoxModel(new String[] { WEEK1, WEEK2, WEEK3, WEEK4, WEEK5, WEEK6, WEEK7, WEEK8, WEEK9, WEEK10, WEEK11, WEEK12, WEEK13, WEEK14, WEEK15, WEEK16, WEEK17, WEEK18, WEEK19, WEEK20, WEEK21, WEEK22, WEEK23, WEEK24, WEEK25, WEEK26  }));
        cmbWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbWeekActionPerformed(evt);
            }
        });

        lblWeek.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblWeek.setText("jLabel2");

        btnOpslaan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOpslaan.setText("Opslaan");
        btnOpslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpslaanActionPerformed(evt);
            }
        });

        btnAnnuleren.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnnuleren.setText("Sluiten");
        btnAnnuleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWeek)
                .addGap(220, 220, 220))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAnnuleren)
                        .addComponent(btnOpslaan)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnuleren, btnOpslaan});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWeek)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpslaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnnuleren)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbWeekActionPerformed
        String selection = cmbWeek.getSelectedItem().toString();
        buildTable(selection);
        setLabelText(selection);
    }//GEN-LAST:event_cmbWeekActionPerformed

    private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpslaanActionPerformed
        opslaan();
    }//GEN-LAST:event_btnOpslaanActionPerformed

    private void btnAnnulerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerenActionPerformed
        if (puntenPage) {
            Punten.closeFrame();
        } else {
            Marsen.closeFrame();
        }
    }//GEN-LAST:event_btnAnnulerenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuleren;
    private javax.swing.JButton btnOpslaan;
    private javax.swing.JComboBox cmbWeek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWeek;
    private javax.swing.JTable tblScores;
    // End of variables declaration//GEN-END:variables
}
