/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Object.Player;
import System.Database;
import System.Main;
import javax.swing.JOptionPane;

/**
 *
 * @author Dave van Rijn, Student 500714558, Klas IS202
 */
public class PlayerPage extends javax.swing.JPanel {

    private boolean newPlayer;
    private final String NEW_PLAYER = "Nieuwe deelnemer";
    private final String EDIT_PLAYER = "Wijzig deelnemer";
    private Player player;

    /**
     * Creates new form Player
     */
    private PlayerPage() {
        initComponents();
    }

    public PlayerPage(boolean newPlayer, Player player) {
        this();
        this.newPlayer = newPlayer;
        if (this.newPlayer) {
            lblTitle.setText(NEW_PLAYER);
            txtFirst.setText("");
            txtInfix.setText("");
            txtLast.setText("");
        } else {
            lblTitle.setText(EDIT_PLAYER);
            this.player = player;
            txtFirst.setText(this.player.getFirstname());
            txtInfix.setText(this.player.getInfix());
            txtLast.setText(this.player.getLastname());
        }
        int size = (int) lblTitle.getSize().getWidth();
        int x = (int) (this.getSize().getWidth() - size) / 2;
        lblTitle.setLocation(x, (int) lblTitle.getLocation().getY());
    }

    private void opslaan() {
        String firstname = txtFirst.getText();
        String infix = txtInfix.getText();
        String lastname = txtLast.getText();
        String mistake = "";
        String velden = "Veld";
        int mistakes = 0;
        if (firstname.isEmpty()) {
            mistake += "'voornaam' ";
            mistakes++;
        }
        if (lastname.isEmpty()) {
            mistake += "'achternaam' ";
            mistakes++;
        }

        if (mistakes > 0) {
            if (mistakes > 1) {
                velden += "en " + mistake + "mogen ";
            } else {
                velden += " " + mistake + "mag ";
            }
            JOptionPane.showMessageDialog(null, velden + "niet leeggelaten worden!",
                    "Fout", JOptionPane.ERROR_MESSAGE);
        } else {
            String result;
            boolean valid = true;
            if (player == null) {
                player = new Player(firstname, infix, lastname);
                for (Player p : Main.getCurrentList()) {
                    if (p.getFullname().equals(player.getFullname())) {
                        valid = false;
                        break;
                    }
                    valid = true;
                }
                if (valid) {
                    player.save();
                }
                result = "De deelnemer is toegevoegd.";
            } else {
                valid = true;
                Database db = new Database();
                player.setFirstname(firstname);
                player.setInfix(infix);
                player.setLastname(lastname);
                db.updatePlayer(player);
                result = "De deelnemer is aangepast.";
            }
            if (valid) {
                JOptionPane.showMessageDialog(null, result, "Succes", JOptionPane.INFORMATION_MESSAGE);
                Deelnemers.closeFrame();
            } else {
                JOptionPane.showMessageDialog(null, 
                        "Er bestaat al een deelnemer met deze voor- en achternaam!",
                        "Fout", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInfix = new javax.swing.JTextField();
        txtFirst = new javax.swing.JTextField();
        txtLast = new javax.swing.JTextField();
        btnOpslaan = new javax.swing.JButton();
        btnAnnuleren = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Voornaam");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tussenvoegsel");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Achternaam");

        txtInfix.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtInfix.setText("jTextField1");
        txtInfix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInfixActionPerformed(evt);
            }
        });

        txtFirst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFirst.setText("jTextField2");
        txtFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstActionPerformed(evt);
            }
        });

        txtLast.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLast.setText("jTextField3");
        txtLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastActionPerformed(evt);
            }
        });

        btnOpslaan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOpslaan.setText("Opslaan");
        btnOpslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpslaanActionPerformed(evt);
            }
        });

        btnAnnuleren.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAnnuleren.setText("Annuleren");
        btnAnnuleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOpslaan)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInfix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAnnuleren))))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFirst, txtInfix, txtLast});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnuleren, btnOpslaan});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInfix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOpslaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnnuleren)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpslaanActionPerformed
        opslaan();
    }//GEN-LAST:event_btnOpslaanActionPerformed

    private void btnAnnulerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerenActionPerformed
        Deelnemers.closeFrame();
    }//GEN-LAST:event_btnAnnulerenActionPerformed

    private void txtFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstActionPerformed
        opslaan();
    }//GEN-LAST:event_txtFirstActionPerformed

    private void txtInfixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfixActionPerformed
        opslaan();
    }//GEN-LAST:event_txtInfixActionPerformed

    private void txtLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastActionPerformed
        opslaan();
    }//GEN-LAST:event_txtLastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuleren;
    private javax.swing.JButton btnOpslaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtInfix;
    private javax.swing.JTextField txtLast;
    // End of variables declaration//GEN-END:variables
}
