/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import System.Main;

/**
 *
 * @author Dave van Rijn, Student 500714558, Klas IS202
 */
public class PrintPage extends javax.swing.JPanel {

    /**
     * Creates new form PrintPage
     */
    public PrintPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLeeg = new javax.swing.JButton();
        btnSpeel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnLeeg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLeeg.setText("Leeg schema");
        btnLeeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeegActionPerformed(evt);
            }
        });

        btnSpeel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSpeel.setText("Speelschema");
        btnSpeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Kies wat je wil printen:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnLeeg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSpeel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeeg, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpeel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeegActionPerformed
        Main.printTable();
        Startpage.closeFrame();
    }//GEN-LAST:event_btnLeegActionPerformed

    private void btnSpeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeelActionPerformed
        Main.printSpeelSchema();
        Startpage.closeFrame();
    }//GEN-LAST:event_btnSpeelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeeg;
    private javax.swing.JButton btnSpeel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
